PROVIDER_CONFIGS: dict[str, dict] = {
    "twitter": {
        "name": "Twitter / X",
        "auth_type": "oauth",
        "authorization_url": "https://twitter.com/i/oauth2/authorize",
        "token_url": "https://api.twitter.com/2/oauth2/token",
        "scopes": ["tweet.read", "tweet.write", "users.read"],
        "client_id_env": "TWITTER_CLIENT_ID",
        "client_secret_env": "TWITTER_CLIENT_SECRET",
        "grant_type": "authorization_code",
    },
    "linkedin": {
        "name": "LinkedIn",
        "auth_type": "oauth",
        "authorization_url": "https://www.linkedin.com/oauth/v2/authorization",
        "token_url": "https://www.linkedin.com/oauth/v2/accessToken",
        "scopes": ["r_liteprofile", "r_emailaddress", "w_member_social"],
        "client_id_env": "LINKEDIN_CLIENT_ID",
        "client_secret_env": "LINKEDIN_CLIENT_SECRET",
        "grant_type": "authorization_code",
    },
    "gmail": {
        "name": "Gmail",
        "auth_type": "oauth",
        "authorization_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/gmail.send", "https://mail.google.com/"],
        "client_id_env": "GOOGLE_CLIENT_ID",
        "client_secret_env": "GOOGLE_CLIENT_SECRET",
        "grant_type": "authorization_code",
    },
    "hubspot": {
        "name": "HubSpot",
        "auth_type": "oauth",
        "authorization_url": "https://app.hubspot.com/oauth/authorize",
        "token_url": "https://api.hubapi.com/oauth/v1/token",
        "scopes": ["contacts", "content"],
        "client_id_env": "HUBSPOT_CLIENT_ID",
        "client_secret_env": "HUBSPOT_CLIENT_SECRET",
        "grant_type": "authorization_code",
    },
    "facebook": {
        "name": "Facebook",
        "auth_type": "oauth",
        "authorization_url": "https://www.facebook.com/v19.0/dialog/oauth",
        "token_url": "https://graph.facebook.com/v19.0/oauth/access_token",
        "scopes": [
            "pages_manage_posts",
            "pages_read_engagement",
            "pages_show_list",
            "instagram_basic",
            "instagram_content_publish",
            "instagram_manage_insights",
        ],
        "client_id_env": "FACEBOOK_CLIENT_ID",
        "client_secret_env": "FACEBOOK_CLIENT_SECRET",
        "redirect_uri_env": "FACEBOOK_REDIRECT_URI",
        "token_exchange": "standard",
        "requires_page_token": True,
        "grant_type": "authorization_code",
    },
    "instagram": {
        "name": "Instagram",
        "auth_type": "oauth",
        "authorization_url": "https://www.facebook.com/v19.0/dialog/oauth",
        "token_url": "https://graph.facebook.com/v19.0/oauth/access_token",
        "scopes": [
            "instagram_basic",
            "instagram_content_publish",
            "instagram_manage_insights",
            "pages_show_list",
        ],
        "client_id_env": "FACEBOOK_CLIENT_ID",
        "client_secret_env": "FACEBOOK_CLIENT_SECRET",
        "redirect_uri_env": "FACEBOOK_REDIRECT_URI",
        "token_exchange": "standard",
        "requires_ig_account_discovery": True,
        "grant_type": "authorization_code",
    },
    "tiktok": {
        "name": "TikTok",
        "auth_type": "oauth",
        "authorization_url": "https://www.tiktok.com/v2/auth/authorize/",
        "token_url": "https://open.tiktokapis.com/v2/oauth/token/",
        "scopes": ["user.info.basic", "video.upload", "video.publish"],
        "client_id_env": "TIKTOK_CLIENT_KEY",
        "client_secret_env": "TIKTOK_CLIENT_SECRET",
        "redirect_uri_env": "TIKTOK_REDIRECT_URI",
        "token_exchange": "tiktok",
        "pkce_required": True,
        "grant_type": "authorization_code",
        "token_expires_in": 86400,
        "refresh_expires_in": 31536000,
    },
    "threads": {
        "name": "Threads",
        "auth_type": "oauth",
        "authorization_url": "https://threads.net/oauth/authorize",
        "token_url": "https://graph.threads.net/oauth/access_token",
        "scopes": [
            "threads_basic",
            "threads_content_publish",
            "threads_read_replies",
            "threads_manage_replies",
            "threads_manage_insights",
        ],
        "client_id_env": "THREADS_CLIENT_ID",
        "client_secret_env": "THREADS_CLIENT_SECRET",
        "redirect_uri_env": "THREADS_REDIRECT_URI",
        "token_exchange": "standard",
        "long_lived_exchange": True,
        "long_lived_url": "https://graph.threads.net/access_token",
        "grant_type": "authorization_code",
    },
}
